package de.simonsator.partyandfriends.main.startup.error;

public enum BootErrorType {
	MYSQL_CONNECTION_PROBLEM, TOO_OLD_VERSION, SHA_ENCRYPTED_PASSWORD, MISSING_PERMISSION_REFERENCE_COMMAND, MARIA_DB_DOWNLOAD_FAILED, MARIA_DB_DRIVER_LOADING_FAILED
}
